### ISSUE TITLE
Incorporate Functions From `virtool.pathoscope`. 

### ISSUE THREAD

**Issue by BlakeASmith** [virtool/workflow-pathoscope#3]
The original [`pathoscope` job](https://github.com/virtool/virtool/blob/release-5.0.0/virtool/jobs/pathoscope.py) from [virtool/virtool](https://github.com/virtool/virtool) utilises the [virtool.pathoscope](https://github.com/virtool/virtool/blob/release-5.0.0/virtool/pathoscope.py) module. 

As such, `virtool.pathoscope` will need to be ported into this repository. `virtool.pathoscope` does not depend on any other modules from `virtool/virtool`, so it should be able to copied in directly to `workflow-pathoscope/pathoscope.py`. 

Any unit tests for `virtool.pathoscope` should be included as well under [`virtool-pathoscope/tests`](https://github.com/virtool/workflow-pathoscope/tree/master/tests) in a file called `test_pathoscope.py`.

**Comment by BlakeASmith** [comment]
The documentation of [virtool.pathoscope](https://github.com/virtool/virtool/blob/release-5.0.0/virtool/pathoscope.py) should be improved as well. 

[ ] Add docstrings to all functions
	[ ] Include descriptions of parameters such as `u` and `nu` 
[ ] Add type hinting to all functions
[ ] Add a module docstring describing the general purpose of the module.

**Comment by igboyes** [comment]
> The documentation of [virtool.pathoscope](https://github.com/virtool/virtool/blob/release-5.0.0/virtool/pathoscope.py) should be improved as well.

Mallory has been working on this already so please see what she contributes before starting.
